server:
  port: 8081
spring:
  application:
    name: fraudService
  datasource:
    username: 'abdelkalek'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
